services:
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/product_db
      - REDIS_URL=redis://redis:6379
      - QUEUE_HOST=redis://redis:6379
    depends_on:
      - mongodb
      - redis

  review-processing-service-1:
    build:
      context: ./review-service
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/product_db
      - REDIS_URL=redis://redis:6379
      - QUEUE_HOST=redis://redis:6379
    depends_on:
      - mongodb
      - redis

  review-processing-service-2:
    build:
      context: ./review-service
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/product_db
      - REDIS_URL=redis://redis:6379
      - QUEUE_HOST=redis://redis:6379
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mongodb_data: